service: samples-todo-api
frameworkVersion: "^1.18.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage}
  region: ${opt:region}
  timeout: 10
  memorySize: 256
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*" 

package:
  exclude:
    - node_modules/**/README*
    - node_modules/**/LICENSE*
    - node_modules/**/*.md
    - node_modules/**/*.html
    - node_modules/**/*.png
    - node_modules/**/test/**
    - node_modules/aws-sdk/**
    - target/**
    - src/**
    - test/**
    - "*.json"
    - "*.md"
    - ".tsconfig/**"
  include:
    - package.json
    - target/dist/**/*.js

functions:
  core:
    handler: target/dist/api.proxyRouter
    events:
      - http:
          path: users/me
          method: get
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: Samples_Todo_Users_${opt:stage}
        AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        KeySchema:
        - AttributeName: userId
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
