version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10
    steps:
      - run:
          name: Check system information
          command: |
            echo "node $(node -v)"
            echo "npm v$(npm -v)"
      - checkout
      - run:
          name: Build
          command: npm run setup
